# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[](surface0)\
$time\
[](bg:red fg:surface0)\
$username\
[](fg:red bg:mauve)\
$directory\
[](fg:mauve bg:sky)\
$git_branch\
[](fg:sky)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[username]
show_always = true
style_user = "bg:red fg:mantle"
style_root = "bg:red fg:mantle"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:mauve"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "fg:base bg:sky"
format = '[ $symbol $branch ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:text bg:surface0"
format = '[ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:green)'
error_symbol = '[ ](bold fg:red)'